Require specific version (seems to be obligatory)
Otherwise, we get:
Error: Unable to resolve action `slsa-framework/slsa-verifier@v2`,
unable to find version `v2`